sudo: false
language: node_js
node_js:
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/socialc0de/germany-says-welcome-website.git
  - secure: eanO8vTAooDopskbznBiITDXumZWzSGtSK8cENVL4ae1ymjhjsUBKticxzglsc5zQDrU2nZyfBPK4Fr7jjxr9ropsBTsS0J6/GFimvYWHlMNLrGd56AGsq80CvuNW68bUI4JuzsQ2+tUGNsfiFmPtzhRXEzex8cCVVzTdrn0S58B4E2gVbmrEum84UXXaAP4GQUciSAgtsCPm0GIujCiDbw1cAHNzKnXxciWwTrboiHkpv/uLKJ+E8JVf5yTCP8WrKaUx7aOom3Mth+X2xeihCWm3JiD8cEps1aedNTbBsLPB/KJCLd0wr83vs72LzqAUFMmBbLnmVtFcG9yCANPZLCWq7SsuCfbzakAg96e1A3uCTl3TlGJV/p3kepnm7EPytaYekpzDWerVHJUqh4UulPdVMCOgs910xVr7efkg0X5jk/ntv91vXM2GJ8oFtk5cyYu85KUp0wU6I8kGK6wAMO/+yDRVOuaiguwl+s7iX7AFO35eS8KdwYGSxgDqZIL6iO/ZmT3ehT6krLfBoHZrvLWw8RbZyJNweG25r8lMrmQKAs535eojCEkHp630r9+J8yHriSF6FHslJ8Eak6EJv8vEgN68Um+b9SiiysBpdftO8cMqRGXxCsi2Zprhti4cPYUNX1maqWpbq3Bp9Kz1f4QTpVAoXLGqXwEp/b5Vw8=
